language: cpp

branches:
  only:
    - master
    - coverity_scan

dist: trusty

before_install:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo add-apt-repository ppa:beineri/opt-qt562-trusty -y
- sudo apt-get update -qq

install:
- sudo apt-get install -y --force-yes -qq g++-6 gcc-6; export CXX="g++-6" CC="gcc-6"; $CXX --version
- sudo apt-get install -y --force-yes -qq qt56base qt56declarative; source /opt/qt56/bin/qt56-env.sh

script:
  - mkdir build
  - cd build
  - qmake ../gui/qt
  - make -j4 CC=gcc-6 CXX=g++-6 LINK=g++-6
  - cd ../core
  - make -j4 CC=gcc-6 CXX=g++-6 LINK=g++-6 clean all

notifications:
  irc:
    channels:
      - "irc.choopa.net#cemu-dev"
    on_success: change
    on_failure: always
    skip_join: true
