language: cpp

branches:
  only:
    - master
    - coverity_scan
    - gh-pages-dev
    - website-dev
    - feature/lcd-spi

sudo: false
os: linux
dist: trusty

env:
  - PATH=/opt/qt56/bin:/usr/local/opt/qt5/bin:$PATH

addons:
  apt:
    sources:
      - sourceline: 'ppa:beineri/opt-qt563-trusty'
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - gcc-5
      - g++-5
      - qt56base
      - libgl1-mesa-dev

script:
  - cd gui/qt/capture && bash ./get_libpng-apng.sh && cd ../../../
  - mkdir build
  - cd build
  - qmake ../gui/qt && make -j4 CC=gcc-5 CXX=g++-5 LINK=g++-5
  - cd ../core
  - make clean && make -j4 CC=gcc-5 CXX=g++-5 LINK=g++-5 all
  - cd ../tests/autotester
  - make clean && make -j4 CC=gcc-5 CXX=g++-5 LINK=g++-5 all

notifications:
  irc:
    channels:
      - "irc.choopa.net#cemu-dev"
    on_success: change
    on_failure: always
    skip_join: true
