language: cpp

branches:
  only:
    - master
    - coverity_scan

before_install:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y --force-yes
- sudo add-apt-repository ppa:beineri/opt-qt551 -y --force-yes
- sudo apt-get update -qq

install:
- sudo apt-get install -qq g++-5 gcc-5; export CXX="g++-5" CC="gcc-5"; $CXX --version
- sudo apt-get install -qq qt55base qt55declarative; source /opt/qt55/bin/qt55-env.sh

script:
  - mkdir build
  - cd build
  - qmake ../gui/qt
  - make -j4 CC=gcc-5 CXX=g++-5 LINK=g++-5
  - cd ../core
  - make -j4 CC=gcc-5 CXX=g++-5 LINK=g++-5 clean all

notifications:
  irc:
    channels:
      - "irc.choopa.net#cemu-dev"
    on_success: change
    on_failure: always
    skip_join: true
