language: python

before_install:
  - sudo apt-get update -qq

script:
  - ./deploy_travisci.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: final-html
  on:
    branch: master
